prostartup/Messenger/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required


app_name = 'Messenger'

urlpatterns = [
    url(r'^dialogs/$', login_required(views.DialogsView.as_view()), name='dialogs'),
    url(r'^dialogs/create/(?P<user_id>\d+)/$', login_required(views.CreateDialogView.as_view()), name='create_dialog'),
    url(r'^dialogs/(?P<chat_id>\d+)/$', login_required(views.MessagesView.as_view()), name='messages'),
    url(r'^dialogs/(?P<chat_id>\d+)/remove/$', login_required(views.Clear_ChatView.as_view()), name='clear_chatView'),

    url(r'^dialogs/all_from_json/(?P<chat_id>\d+)/$', login_required(views.filter), name='all_from_json'),
    # url(r'^dialogs/(?P<chat_id>\d+)/delete/$', login_required(views.Clear_Chat), name='messages_delete'),
   
]

prostartup/Offers/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required


app_name = 'Offers'

urlpatterns = [
    url(r'^account/offers/$', login_required(views.OffersAllView.as_view()), name='offers'),
    url(r'^account/offers/create/(?P<project_id>\d+)/(?P<user_id>\d+)/$', login_required(views.CreateOffersView.as_view()), name='create_offer'),
    url(r'^account/offers/remove/(?P<offer_id>\d+)/$', login_required(views.OffersRemoveView.as_view()), name='remove_offer'),
    
    url(r'^account/contract/$', login_required(views.ContractView.as_view()), name = 'contract'),
    url(r'^account/contract/(?P<contract_id>\d+)/$', login_required(views.ContractDatailView.as_view()), name = 'contract_detail'),
    url(r'^account/contract/create/(?P<offer_id>\d+)/$', login_required(views.ContractCreateView.as_view()), name = 'contract_create'),
    # url(r'^$', login_required(views.ContractView.as_view()), name = 'contract'),
   
]

prostartup/prostartup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, handler404, handler500 
from Account.views import logout_view

handler404 = 'PageControll.views.e_handler404'
handler500 = 'PageControll.views.e_handler500'

urlpatterns = [
    path('admin/logout/', logout_view, name='logout'),
    path('admin/', admin.site.urls),
   
]

#My urls
urlpatterns += [
    path('',         include('ProjectManager.urls')),
    path('account/', include('Account.urls')),
     
    path('account/messege/', include(('Messenger.urls', 'Messenger'), namespace='Messenger')),
    path('account/payment/', include('Payment.urls')),
    path('',  include(('Offers.urls', 'Offers'), namespace='Offers')),
    path('',  include('PageControll.urls')),

] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

prostartup/Messenger/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse


class ChatManager(models.Manager):
    use_for_related_fields = True
 
    # Метод принимает пользователя, для которого должна производиться выборка
    # Если пользователь не добавлен, то будет возвращены все диалоги,
    # в которых хотя бы одно сообщение не прочитано
    def unreaded(self, user=None):
        qs = self.get_queryset().exclude(last_message__isnull=True).filter(last_message__is_readed=False)
        return qs.exclude(last_message__author=user) if user else qs

 
class Chat(models.Model):
    DIALOG = 'D'
    CHAT = 'C'
    CHAT_TYPE_CHOICES = (
        (DIALOG, _('Dialog')),
        (CHAT, _('Chat'))
    )
 
    type = models.CharField(
        _('Тип'),
        max_length=1,
        choices=CHAT_TYPE_CHOICES,
        default=DIALOG
    )
    members = models.ManyToManyField(User, verbose_name=_("Участник"))
    last_message = models.ForeignKey('Message', related_name='last_message', null=True, blank=True, on_delete=models.SET_NULL)
 
    objects = ChatManager()

    def get_absolute_url(self):
        return reverse('Messenger:messages', args=[self.pk])
 
 
class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name =_("Чат"), on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name=_("Пользователь"),on_delete=models.CASCADE)
    message = models.TextField(_("Сообщение"))
    pub_date = models.DateTimeField(_('Дата сообщения'), default=timezone.now)
    is_readed = models.BooleanField(_('Прочитано'), default=False)
 
    class Meta:
        ordering=['pub_date']
 
    def __str__(self):
        return self.message

class SettingsChat(models.Model):
    chat = models.ForeignKey(Chat, verbose_name =_("Настройки сообщений"), on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name=_("Пользователь"),on_delete=models.CASCADE, default="")
    visibility = models.BooleanField(default = True)

prostartup/templates/users/dialogs.html
{% extends 'Account/base_account.html' %}
{% load chat_tag %}

{% load accaunt_redir_extras %}
{% block content %}

<div class="admin__dialogs">
    <style>
        .unreaded>a {
            color: red;
        }
    </style>
    {% load tz %}

    {% if chats.count == 0 %}
    <div class="admin__title">Нет ни одного начатого диалога</div>
    <div class="dialogs__title">Нет ни одного начатого диалога</div>
    {% endif %}
    <div class="admin__title">Диалоги</div>
    <div class="dialogs__title">Диалоги</div>
    <div class="count"> У вас {{count_is_readed}} не прочитаный сообщений ! </div>
    <div class="admin__dialogs-items">
        {% for setting in settings %}
        {% if setting.visibility %}
        {% for chat in chats %}
        {% if chat.message_set.count != 0 %}
        {% with last_message=chat.message_set.last %}

        {% get_companion user chat as companion %}

        <a href="{{ chat.get_absolute_url }}" class="admin__dialogs-item">
            <div class="user-image">
                {% if companion|personal_data %}
                <img src="{{ companion|personal_data  }}" alt="Profile image">
                {% endif %}
            </div>
            <div class="user-message">
                <div class="message-content">
                    <div class="user-name">{{ companion.first_name }} {{ companion.last_name }}</div>
                    <div class="user-message__text">{{ last_message.message|truncatechars_html:"20"|safe|striptags }}
                    </div>
                </div>
                <div class="message-info" style="margin-right: 16px;">
                    <div class="message-time">{{ last_message.pub_date|utc }}</div>
                    {% if companion != last_message.author %}
                    <div class="unread">
                        <span class="material-icons">
                            {% if not last_message.is_readed %}done {% else %} done_all {% endif %}
                        </span>
                    </div>
                    {% endif %}
                </div>
            </div>
        </a>
        <!-- <td><a href="{% url 'Messenger:clear_chatView' chat.id %}">Delete</a></td> -->
        {% endwith %}
        {% endif %}
        {% endfor %}
        {% endif %}
        {% endfor %}

    </div>
</div>
{% endblock %}

prostartup/templates/users/messeg.html
{% extends 'Account/base_account.html' %}
{% load accaunt_redir_extras %}
{% load chat_tag %}
{% load static %}
{% block content %}


<div class="style-text-black" style="color: black !important;">
    {% if not chat %}
    <div class="panel panel-body">
        "Невозможно начать беседу. Не найден пользователь или вы не имеете доступа к данной беседе."
    </div>
    {% else %}
    {% load tz %}
    {% if chat %}
    <div class="panel">
        <div id="innerMessages" class="scroll">
        </div>
    </div>
    {% endif %}
    <div id="message_form" class="message_form">
        <form id="message-form" class="panel panel-body" method="post">
            {% csrf_token %}
            {{form}}
            <button type="submit" class="btn btn-default btn-sm"><span class="ico ico-comment"></span>Отправить</button>
        </form>
    </div>

    {% endif %}

</div>




<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>
<script type="text/javascript">
</script>
<script type="text/javascript">
    function parse_data(data) {

        var data = data;
        var list = []
        var data_mess = '';

        for (i in data) {
            list[i] = [{ 'author': data[i].author, 'message': data[i].message ,'is_readed' : data[i].is_readed}]
        }
        for (i in list) {
            for (t of list[i]) {
                var when_mess = '';
                var is_readed = '';
                var unreaded = t.is_readed;
                // console.log(!Boolean(unreaded));
                if ('{{request.user.username}}' == t.author) {
                    when_mess = 'message_from';
                } else {
                    when_mess = 'message_to';
                }

                var un_read = '';
                if(unreaded){
                    un_read = 'readed'
                } else{
                    un_read = 'unreaded'
                }
                // console.log(data_mess);
                data_mess += '<div class="list-group-item '+ un_read +' "> <div class="group ' + when_mess + ' "><span><small>'
                    + t.author +
                    '</small></span><div class="message">'
                    + t.message +
                    '</div></div></div>';
            }
        }
        document.getElementById('innerMessages').innerHTML = data_mess;
    }
    function show() {
        $.ajax({
            url: "{% url 'Messenger:all_from_json' ID_PAGE%}",
            dataType: 'json',
            success: function (response) {


                parse_data(response);
                $('#innerMessages').scrollTop(99999);
            }
        });
    }

    $(document).ready(function () {
        var time = 35000;
        show();
        setInterval('show()', time);
    });
</script>
{% endblock %}