prostartup/Messenger/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required


app_name = 'Messenger'

urlpatterns = [
    url(r'^dialogs/$', login_required(views.DialogsView.as_view()), name='dialogs'),
    url(r'^dialogs/create/(?P<user_id>\d+)/$', login_required(views.CreateDialogView.as_view()), name='create_dialog'),
    url(r'^dialogs/(?P<chat_id>\d+)/$', login_required(views.MessagesView.as_view()), name='messages'),
    url(r'^dialogs/(?P<chat_id>\d+)/remove/$', login_required(views.Clear_ChatView.as_view()), name='clear_chatView'),

    url(r'^dialogs/all_from_json/(?P<chat_id>\d+)/$', login_required(views.filter), name='all_from_json'),
    # url(r'^dialogs/(?P<chat_id>\d+)/delete/$', login_required(views.Clear_Chat), name='messages_delete'),
   
]

prostartup/Offers/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required


app_name = 'Offers'

urlpatterns = [
    url(r'^account/offers/$', login_required(views.OffersAllView.as_view()), name='offers'),
    url(r'^account/offers/create/(?P<project_id>\d+)/(?P<user_id>\d+)/$', login_required(views.CreateOffersView.as_view()), name='create_offer'),
    url(r'^account/offers/remove/(?P<offer_id>\d+)/$', login_required(views.OffersRemoveView.as_view()), name='remove_offer'),
    
    url(r'^account/contract/$', login_required(views.ContractView.as_view()), name = 'contract'),
    url(r'^account/contract/(?P<contract_id>\d+)/$', login_required(views.ContractDatailView.as_view()), name = 'contract_detail'),
    url(r'^account/contract/create/(?P<offer_id>\d+)/$', login_required(views.ContractCreateView.as_view()), name = 'contract_create'),
    # url(r'^$', login_required(views.ContractView.as_view()), name = 'contract'),
   
]

prostartup/ProjectManager/urls.py
from django.urls import path,include
from . import views
from django.conf.urls import url
# from .models import BookmarkProject
from django.contrib.auth.decorators import login_required

urlpatterns = [
    
    path('project-list/search/', views.SearchFilter.as_view(), name='SearchFilter'),
    path('project-list/filter/', views.FilterProject.as_view(), name='FilterProject'),
    path('project-list/', views.ProjectListView.as_view(), name='project_list'),
    url(r'^project-detail/(?P<pk>\w+)/$', views.Project_Detai, name='project_detail'),

    path('account/favorites/', views.Favorite_detail, name='Favorite_detail'),
    path('account/favorites/add/<int:project_id>/', views.Favorite_add, name='Favorite_add'),
    path('account/favorites/remove/<int:project_id>/', views.Favorite_remove, name='Favorite_remove'),
    
]

prostartup/prostartup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, handler404, handler500 
from Account.views import logout_view

handler404 = 'PageControll.views.e_handler404'
handler500 = 'PageControll.views.e_handler500'

urlpatterns = [
    path('admin/logout/', logout_view, name='logout'),
    path('admin/', admin.site.urls),
   
]

#My urls
urlpatterns += [
    path('',         include('ProjectManager.urls')),
    path('account/', include('Account.urls')),
     
    path('account/messege/', include(('Messenger.urls', 'Messenger'), namespace='Messenger')),
    path('account/payment/', include('Payment.urls')),
    path('',  include(('Offers.urls', 'Offers'), namespace='Offers')),
    path('',  include('PageControll.urls')),

] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

prostartup/ProjectManager/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib import auth
from django.conf import settings
from django.utils.text import slugify



class Category(models.Model):
    """Категории"""
    # name - Имя категории 
    name = models.CharField("Категория", max_length=150)

    # url - Ссылка на категории 
    url = models.SlugField(max_length=160, unique=True)


    def __str__(self): 
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"



class ProjectManager():
    """Параметры проекта"""
    CHOICES_PROJECT = (
        ('Selling', 'Selling'),
        ('Investing', 'Investing'),
    )       

    

class Project(models.Model):
    """Проект"""

    # Имя проекта 
    project_name = models.CharField("Название проекта", max_length = 100)

    # Связь со всеми категориями на сайте 
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete = models.SET_NULL, null = True)

    # Призентация 
    presentation = models.TextField("Описание проекта")
    
    # Тип проекта 
    choices = models.CharField(max_length = 15, choices = ProjectManager().CHOICES_PROJECT, default='investing')
    
    # Полное описание для проекта 
    full_project_description = models.FileField("Полное описание проекта", upload_to='uploads/%Y/%m/%d/',blank=False)
    
    # Бизнес план 
    business_plan = models.FileField("Бизнес план", upload_to='uploads/%Y/%m/%d/',blank=False)

    # Фото проекта 
    project_img_one = models.ImageField( upload_to='uploads/images/%Y/%m/%d/',blank=True)

    # Фото проекта 
    project_img_two = models.ImageField( upload_to='uploads/images/%Y/%m/%d/',blank=True)

    # Фото проекта 
    project_img_three = models.ImageField( upload_to='uploads/images/%Y/%m/%d/',blank=True)

    
    # Ссылка на проект 
    slug = models.SlugField(max_length=130, unique=False)
    
    # Черновой вариант 
    draft = models.BooleanField("Черновик", default = False)
    
    # Стоимость проекта 
    project_cost = models.PositiveIntegerField("Стоимость проекта",  help_text = "Указывать сумму в рублях",default=0)
    
    # Сумма инвестиции 
    project_investment  = models.PositiveIntegerField("Сумма инвестиции",  help_text = "Указывать сумму в рублях", blank=True,default=0)
    
    # Универсальность проекта 
    universality = models.BooleanField("Универсальность проека", default = False)
    
    # Статус проверки на корректность 
    status_active_of_project = models.BooleanField("Статус активности проекта", default = False)#
    
    # Дата публикации 
    publication_date = models.DateField("Дата публикации", default=date.today, db_index=True)
    
    # Автор поекта 
    project_author = models.ForeignKey(User, on_delete=models.CASCADE)

    # Продвижение в топ 
    promotions = models.BooleanField("Продвижение проекта", default = False)

    # Статус оплаты  
    payment_state = models.BooleanField("Статус оплаты", default = False)

    #Статус завершения проекта
    project_comletion = models.BooleanField("Статус завершения проекта", default = False)

    #Число просмотров 
    count_views_project = models.PositiveIntegerField('Число просмотров', blank = True, default=0)

    # popular = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='Популярность проекта', blank=True)
    
    def __str__(self):
        return self.project_name

    def get_absolute_url(self):
        return reverse('project_detail', args=[str(self.id)])

    class Meta:
        verbose_name = "Проект"
        verbose_name_plural = "Проекты"



class ProjectaAnalytics(models.Model):
    class Meta:
        db_table = "ProjectaAnalytics"

    # внешний ключ на статью
    project = models.ForeignKey(Project, on_delete = models.CASCADE ) 

    # количество просмотров в эту дату
    views = models.IntegerField('Просмотры', default=0) 

    def __str__(self):
        return self.project.project_name

prostartup/ProjectManager/forms.py
from django import forms
from .models import Project


class FavoriteAddProjectForm(forms.Form):
    ids = forms.IntegerField(required=False,initial=False,widget=forms.HiddenInput)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

# class ProjectCreateForm(forms.ModelForm):
#     def clean_fields(self):
#         cd = self.cleaned_data
#         return cd


#     class Meta:
#         model = Project
#         fields = ('project_name', 'slug', 'category','presentation','full_project_description', 'business_plan', 'project_cost', 'project_investment','status_active_of_project')



        

prostartup/ProjectManager/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Category, Project, ProjectaAnalytics,ProjectManager
from django.views import generic
from .forms import  FavoriteAddProjectForm
from django.contrib import messages
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import Group
from .favorites import Favorite
from django.views.decorators.http import require_POST
from datetime import date
from django.utils import timezone
from Account.models import Subscription
from Account.models import Profile
from django.contrib.auth.models import User
from django.db.models import Q


class Filter_data_Project:
    def get_category(self):
        return Category.objects.all()

    def get_type(self):
        return ProjectManager.CHOICES_PROJECT

class ProjectListView(Filter_data_Project, generic.ListView):
    """Страница со списком проектов"""
    model = Project
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['chek_subscribe'] = Subscription.objects.get(user = self.request.user).subscription_end_date
        context['today_date'] = date.today
        self.queryset = Project.objects.filter(project_comletion = False).order_by('-publication_date')
        promotions = self.queryset.filter(promotions = True)
        project_list = []

        # Цикл формирует сортировку списка с проектами 
        for index, project in enumerate(self.queryset):
            for promotion in promotions:
                if index in [5,10,15]: # Периуд индекса через n проходов чтобы чаще встречались продвигаемые проекты  !
                    project_list.append(promotion)
                    if promotion in project_list:
                        break
            project_list.append(project)
            

        print(project_list)

        context['project_list'] = project_list
        return context# Проверка на подписку 
    # elif has_group(request.user, "Seller") or has_group(request.user, "Investor"):
        


def Project_Detai(request, pk):
    """Страница с детальным разбором проекта"""
    projects = Project.objects.filter(pk=pk) 

    """Получение / Создание счётчика посещений на страницу с определённым pk"""
    obj, created = ProjectaAnalytics.objects.get_or_create(
        defaults={
            "project": projects[0],
        }, 
            project = projects[0],
        )
    obj.views += 1  # Увелечение счётчика при каждом посещении 
    obj.save(update_fields=['views']) #Обнавление поля просмотров

    #Объект для обновления поля просмотров у проекта 
    projects_update = Project.objects.get(id = projects[0].id)
    projects_update.count_views_project = obj.views
    projects_update.save(update_fields=['count_views_project'])#Обнавление поля числа просмотров у проекта 

    views = ProjectaAnalytics.objects.filter(project = projects[0]) #Вывод Кол-во просмотров проекта 
    contact_data = Profile.objects.get(user = projects[0].project_author)
    contact_data_email = User.objects.get(id = projects[0].project_author.id).email

    context = {
        'projects': projects,
        'form' : FavoriteAddProjectForm(),
        'views' : views,
        'contact_data': contact_data,
        'contact_data_email':contact_data_email,
    }

    return render(request , 'ProjectManager/project_detail.html', context)


class SearchFilter(generic.ListView):
    def get_queryset(self):
        return Project.objects.filter(project_name__icontains = self.request.GET.get('q'))
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get('q')
        context['chek_subscribe'] = Subscription.objects.get(user = self.request.user).subscription_end_date
        context['today_date'] = date.today
        return context


class FilterProject(Filter_data_Project, generic.ListView):
    def get_queryset(self):
        
        queryset = Project.objects.filter(
                Q(category__in = self.request.GET.getlist('category')) |  
                Q(choices__in = self.request.GET.getlist('choices')) 
            )
        return queryset

def Favorite_add(request, project_id):
    if  has_group(request.user, "Seller"):
        return redirect('/account/')
    """Функция добавления сессии на избранные проекты"""
    favorite = Favorite(request) # Получение экземпляра сессии 
    project = get_object_or_404(Project, id=project_id) # Получение id проекта 
    favorite.add(project=project,
                        ids=True)
    return redirect('Favorite_detail')


def Favorite_remove(request, project_id):
    """Функция удаление сессии на избранные проекты"""
    if  has_group(request.user, "Seller"):
        return redirect('/account/')
    favorite = Favorite(request)
    project = get_object_or_404(Project, id=project_id)
    favorite.remove(project)
    return redirect('Favorite_detail')


def Favorite_detail(request):
    """Страница со всеми проетами"""
    if  has_group(request.user, "Seller"):
        return redirect('/account/')
    favorite = Favorite(request)
    return render(request, 'Account/favorite_detail.html', {'favorite': favorite})



    


def has_group(user, group_name): 
    try: 
        group = Group.objects.get(name=group_name) 
    except Group.DoesNotExist: 
        return False
    return group in user.groups.all() 

prostartup/templates/ProjectManager/project_confirm_delete.html
{% extends 'Account/base_account.html' %}

{% load accaunt_redir_extras %}
{% block content %}

<div class="style-text-black" style="color: black !important;">
<p>Are you sure you want to delete the project: {{ project }}?</p>
<form action="." method="post">
    {% csrf_token %}
    <input type="submit" value="Success">
</form>
</div>
{% endblock %}

prostartup/templates/ProjectManager/project_detail.html
{% extends 'Account/base_account.html' %}
{% load accaunt_redir_extras %}
{% load static %}
{% block content %}
{% for project in projects %}
<div style="color: #06005D;" class="admin__content-details">
    <div class="admin__content-details__header">

        <div class="details__header-userInfo">
            <div class="details__header-userInfo__photo">
                {% if project.project_author|personal_data %}
                    <img src="{{ project.project_author|personal_data  }}" alt="Profile image">
                {% endif %}
            </div>
            <div class="details__header-userInfo__about-name">{{project.project_author.first_name}} {{project.project_author.last_name}}</div>
            {% if not request.user|has_group:"Seller"  %}
                {% if not contact_data.hide_personal_data %}
                <div class="user-card">
                    <ul class="user-card__info">
                        <li>Телефон: <a href="tel:{{contact_data.phone}}">{{contact_data.phone}}</a></li>
                        <li>E-mail: <a href="email:{{contact_data_email}}">{{contact_data_email}}</a></li>
                    </ul>
                </div>
                {% endif %}
            {% endif %}
        </div>
        <div class="details__header-userStatistic">
            <div class="details__header-userStatistic__rating">
                {{project.publication_date}}
            </div>
            <div class="details__header-userStatistic__views">
                {% for view in views %}
                <span><img src="{% static 'img/views.svg' %}" alt=""></span>{{view.views}}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="admin__content-details__main">
        <div class="details__main-inner">
            <div class="details__main-preview">
                <div class="preview__img-primary">
                    {% if project.project_img_one %}
                    <img src="{{project.project_img_one.url}}">
                    {% endif %}
                </div>
                <div class="preview__img-secondary">
                    <div class="secondary_img1">
                        {% if project.project_img_two %}
                        <img src="{{project.project_img_two.url}}">
                        {% endif %}
                    </div>
                    <div class="secondary_img2">
                        {% if project.project_img_three %}
                        <img src="{{project.project_img_three.url}}">
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="details__main-about">
                <div class="details__main-about__info">
                    <h2 class="details__main-about__projectName">{{project.project_name}}</h2>

                    <h4>Категория : {{project.category}}</h4>
                    <h4>Тип проекта: {{project.choices}}</h4>
                    <p class="details__main-about__projectDescr">
                        {{project.presentation}}
                    </p>
                    <div class="download__btns">
                        {% if request.user|has_group:"Seller" and request.user != project.project_author %}
                        <p>Ваша роль не может предоставить вам функционал взаимодействи с проектами !</p>
                        {% else %}
                            <a download href="{{project.full_project_description.url}}" title="download presentation"
                                class="download__btn">Презентация</a>
                            <a download href="{{project.business_plan.url}}" title="download biznes model"
                                class="download__btn">Бизнес
                                модель</a>
                        
                    </div>
                </div>
                <div class="details__main-about__price">
                    <div class="details__main-about__price-cost">
                        <div class="cost__numbers">
                            <span>Стоимость проекта:</span>₽{% if project.choices == 'Selling' %}{{project.project_cost}}{% else %}{{project.project_investment}}{% endif %}
                        </div>
                        {% if request.user != project.project_author %}
                        <a href="{% url 'Offers:create_offer' project.id project.project_author.id %}"
                            title="buy button" class="cost__btn"
                            onclick="JavaScript:return Validator(this.id);">Покупка</a>
                    </div>
                    <div class="details__main-about__price-appendix">
                        <a href="{% url 'Messenger:create_dialog' project.project_author.id %}"
                            class="send__message">Написать автору</a>
                        <a href="{% url "Favorite_add" project.id %}" class="addToFavorites">Добавить в избранное</a>

                        {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    function Validator(id_) {
        if (confirm("Вы подтверждаете операцию?")) {
            document.getElementById(id_).submit();
            return (true);
        } else {
            return (false);
        }
    }
</script>

{% endblock %}

prostartup/templates/ProjectManager/project_form.html
{% extends 'Account/base_account.html' %}

{% load accaunt_redir_extras %}
{% load static %}

{% block content %}

<div class="admin__content-form">
    <div class="admin__title">Добавление проекта </div>
    <div class="add__project">
        <form action="." method="post" enctype="Multipart/form-data">
            {% csrf_token %}
            <div class="add__project-inner">
                <div class="add__project-about">
                    <div class="add__project-about__title">Добавление проекта</div>
                    <div class="add__project-about__descr">
                        <div class="add__project-warning">
                            <div class="warning__title">После добавления проекта с вашего счёта будет
                                снято</div>
                            <div class="warning__image">
                                <img class="blue-coin" src="{% static 'img/coin.svg' %}" alt="coins">
                                <img class="white-coin" src="{% static 'img/white-coin.svg' %}" alt="coins">399₽
                            </div>
                        </div>
                        <div class="add__project-done__btns">
                            <div class="add__project-privacy">
                                <input type="checkbox" checked id="add-privacy" name="add-privacy">
                                <label for="add-privacy"><a href="#">Политика
                                        конфиденциальности</a></label>
                            </div>
                            {% if payment_data < 399 %}
                            <div class="warning__title">На вашем счету не достаточно средств !</div>
                            {% else %}
                                <button id="add-project-btn" type="submit">Выставить</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="add__project-form">
                    <div class="add__project-form__descr">
                        {{ form.project_name  }}<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->
                        {{form.presentation}}
                        <!-- <textarea placeholder=""></textarea> -->
                    </div>
                    <div class="add__project-form__images">
                        <div class="add-img">
                            {{form.project_img_one}}
                            <label for="add-img1">
                                <span class="material-icons">add</span>
                                <div class="js-value">Главная фотография проекта</div>
                            </label>
                        </div>
                        <div class="add-img">
                            {{form.project_img_two}}
                            <label for="add-img2">
                                <span class="material-icons">add</span>
                                <div class="js-value">Фотография проекта</div>
                            </label>
                        </div>
                        <div class="add-img">
                            {{form.project_img_three}}
                            <label for="add-img3">
                                <span class="material-icons">add</span>
                                <div class="js-value">Фотография проекта</div>
                            </label>
                        </div>
                    </div>
                    <div class="add__project-form__files">
                        <div class="file__inputs">
                            {{form.full_project_description}}
                            <label for="presentation">Загрузить презентацию</label>
                            <div class="file__inputs-about">Презентацию можно загружать файлами: .PDF,
                                .PPT </div>
                        </div>
                        <div class="file__inputs">
                            {{form.business_plan}}
                            <label for="plan">Бизнес план проекта</label>
                            <div class="file__inputs-about">Бизнес план можно загружать файлами: .DOCX,
                                .TXT </div>
                        </div>
                        
                        <div class="file__inputs">
                            {{form.choices}} <!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->
                            <div class="file__inputs-about">Выберете тип инвестиция или продажа для
                                дальнейших действий</div>
                        </div>
                        <div class="file__inputs">
                            {{form.project_investment}}
                            <div class="file__inputs-about">Стоимость для инвестора, чтобы он смог с
                                вами сотрудничать</div>
                        </div>
                        <div class="file__inputs">
                            
                            {{form.project_cost}}
                            <div class="file__inputs-about">Стоимость должна быть в допустимых значениях
                            </div>
                        </div>
                        <div class="file__inputs">
                            {{form.category}}
                            <div class="file__inputs-about">Выбор категории проекта помогает быстрее его
                                отыскать.</div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>























<!-- <div class="style-text-black" style="color: black !important;">
    {% if request.user|has_group:"Seller" %}
    <form > -->
        
       
        <!-- <input type="submit" value="Success"> -->
    <!-- </form>
    {% else %}
    <p><b>Нам интересно как вы сюда попали ?</b></p>

    {% endif %}
</div> -->
{% endblock %}

prostartup/templates/ProjectManager/project_list.html
{% extends 'Account/base_account.html' %}

{% load accaunt_redir_extras %}

{% load static %}
<!-- Тут django конструкция  -->

{% block content %}


<div class="admin__content-tables">
  <div class="magazine" style="margin-bottom: 100px;"> 
    <div class="magazine__header">
      <div class="magazine__header-title"><a href="{% url 'project_list' %}" style="color:#00b2e7;">Магазин идей </a>
      </div>
      <div class="magazine__header-search">
        <form method="GET" action="{% url 'SearchFilter' %}">
          <button type="submit">
            <img src="{% static 'img/search.svg' %}" alt="">
          </button>
          <input type="search" name="q" id="search" placeholder="Поиск идеи">
        </form>
      </div>
    </div>
    <div class="magazine__items">

      {% if project_list %}
      {% if today_date < chek_subscribe  or  request.user|has_group:"Seller" %}
      {% for project in project_list %}
      <div class="magazine__items-item" id="project">

        <div class="item__preview-img" {% if project.promotions  %} style="background: rgb(2,0,36);background: linear-gradient(27deg, rgba(2,0,36,1) 0%, rgba(10,9,121,1) 34%, rgba(0,212,255,1) 100%);"{% endif %}>{% if project.project_img_one %}<img
            src="{{project.project_img_one.url}}">{% endif %}</div>
        <div class="item__descr">
          <div class="item__descr-about">
            <div class="item__descr-about__name">{{ project.project_name }}</div>
            <div class="item__descr-about__subdescr">
              {{project.presentation|truncatechars:20}}
            </div>
          </div>
          <div class="item__descr-price">
            <div class="item__descr-price__num">
              ₽{% if project.choices == 'Selling' %}{{project.project_cost}}{% else %}{{project.project_investment}}{% endif %}
            </div>
            <a href="{{ project.get_absolute_url }}" class="detail-view">
              Ознакомиться<span><img src="{% static 'img/about.svg' %}" alt=""></span>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <p>Извините у вас истёк срок подписки </p>
      {% endif %}

      {% else %}
      <p>В машазине отсутствуют проекты по данному запросу !</p>
      {% endif %}
    </div>
    <div class="pagination">
      {% if is_paginated %}
      {% if page_obj.has_previous %}
      <div class="">
        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"><span class="material-icons">
            arrow_back_ios
          </span></a>
      </div>

      {% endif %}
      <div class="" style="margin-right: 5px; font-size: 16px;">
        {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
      </div>

      {% if page_obj.has_next %}
      <div class="">
        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"><span class="material-icons">
            arrow_forward_ios
          </span></a>
      </div>

      {% endif %}
      {% endif %}
      <style>
        .pagination {
          display: flex;
          align-items: center;
          justify-content: flex-end;
        }
      </style>
    </div>
  </div>
  <div class="filter" id="filter">
    <form action="{% url 'FilterProject' %}" method="GET">
      <div class="filter__header">
        <div class="filter__title">
          Фильтр
        </div>
      </div>
      <div class="filter__components">
        <div class="filter__components-component">
          <div class="component__title">Популярность</div>
          <ul class="component__list">
            <li>
              <label for="rating">
                <input id="rating" type="checkbox">Новые идеи
              </label>
            </li>
            <li>
              <label for="rating2">
                <input id="rating2" type="checkbox">Высокий рейтинг
              </label>
            </li>
          </ul>
        </div>
        <div class="filter__components-component">
          <div class="component__title">Тип проекта </div>
          <ul class="component__list">
            {% for type in view.get_type %}
            <li>
              <label for="{{type.0}}">
                <input id="{{type.0}}" type="checkbox" name = "choices" value="{{type.0}}">{{type.0}}
              </label>
            </li>
            {% endfor %}
          </ul>
        </div>
        
        <div class="filter__components-component">
          <div class="component__title">Категория</div>
          <ul class="component__list">
            {% for category in view.get_category %}
            <li>
              <label for="{{category.name}}">
                <input id="{{category.name}}" type="checkbox" name="category" value="{{category.id}}">{{category.name}}
              </label>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>

      <button type="submit">Найти</button>

    </form>
  </div>
</div>
<div class="mobile__btns">
  <div class="mobile__btns-inner">
    <div id="filter-btn" class="mobile__btns-item">
      <a href="#filter">
        <img src="{% static 'img/filter.svg' %}" alt="Filter">
        <div class="item-text">Фильтр</div>
      </a>
    </div>
  </div>
</div>



{% endblock %}
<!-- ({{project.choices}}) ({{project.project_author}} : {{project.project_author.groups.all.0}}) -->